[setup]
boxlength		= 60
zstart			= 100
levelmin		= 7
levelmin_TF		= 9
levelmax		= 12
#padding		= 9
padding			= 16  # try reduce it at your own risk
overlap			= 4
ref_offset		= 0.36, 0.465, 0.64 # halo 9 at z=0.002, but halo 20 at z=1.951
ref_extent		= 0.115, 0.10, 0.11   
align_top		= yes
periodic_TF		= no
baryons			= no
use_2LPT		= no
use_LLA			= no


[cosmology]
Omega_m			= 0.272
Omega_L			= 0.728
Omega_b			= 0.0455
H0				= 70.2
sigma_8			= 0.807
nspec			= 0.961
transfer		= eisenstein

[random]
cubesize		= 256
seed[8]			= 95064
seed[9]			= 31415
seed[10]		= 27183

[output]
## GENERIC
#format			= generic
#filename		= debug.hdf5

## ENZO
format			= enzo
filename		= ic.enzo

## GADGET-2
#shift_back		= yes
#format			= gadget2
#filename		= ics_gadget.dat

## RAMSES
#ramses_nml		= yes
#format			= grafic2
#filename		= ics_ramses

## TIPSY
#format			= tipsy
#filename		= ics_tipsy.dat

[poisson]
fft_fine		= yes
accuracy		= 1e-4
grad_order      = 6
laplace_order   = 6

